import type { Translations } from "./ru";

export const zhCN: Partial<Translations> = {
  app: "应用程序",
  general: "常规",
  hotkeys: "快捷键",
  server: "服务器",
  providers: "提供商",
  models: "模型",
  language: "语言",
  languageDesc: "更改 Premire 的显示语言",
  autoAccept: "自动接受权限",
  autoAcceptDesc: "权限请求将自动获得批准",
  terminalShell: "终端 Shell",
  terminalShellDesc: "内置终端的命令行环境",
  showThinking: "显示推理摘要",
  showThinkingDesc: "显示模型的推理过程",
  theme: "主题",
  themeDesc: "选择应用程序主题",
  colorScheme: "配色方案",
  colorSchemeDesc: "浅色、深色或系统",
  dark: "深色",
  light: "浅色",
  system: "系统",
  font: "字体",
  fontDesc: "主界面字体",
  systemFont: "系统",
  codeFont: "代码字体",
  codeFontDesc: "编辑器和终端的等宽字体",
  soundNotifications: "声音通知",
  soundEnabled: "启用声音",
  soundEnabledDesc: "播放声音通知",
  soundOnComplete: "任务完成",
  soundOnCompleteDesc: "成功完成时播放声音",
  soundOnStop: "任务停止",
  soundOnStopDesc: "强制停止时播放声音",
  connectedProviders: "已连接的提供商",
  disconnect: "断开",
  connect: "连接",
  customProvider: "自定义提供商",
  searchModels: "搜索模型...",
  loadingModels: "加载模型中...",
  noModels: "请至少连接一个提供商以查看模型列表。",
  editProvider: "编辑提供商",
  customProviderTitle: "自定义提供商",
  name: "名称",
  hideKey: "隐藏密钥",
  showKey: "显示密钥",
  save: "保存",
  newSession: "新会话",
  prevSession: "上一个会话",
  nextSession: "下一个会话",
  openTerminal: "打开终端",
  searchPlaceholder: "搜索命令、文件...",
  searchIn: "在 {folder} 中搜索",
  menu: "菜单",
  hideSessions: "隐藏会话",
  showSessions: "显示会话",
  newSessionTitle: "新会话",
  prevSessionTitle: "上一个会话",
  nextSessionTitle: "下一个会话",
  toggleTerminal: "切换终端",
  toggleSessions: "切换会话",
  hideFileTree: "隐藏文件树",
  showFileTree: "显示文件树",
  toggleFileTree: "切换文件树",
  close: "关闭",
  minimizeLabel: "最小化",
  maximizeLabel: "最大化",
  closeLabel: "关闭",
  welcomeSubtitle: "没有打开的项目。选择一个文件夹以在其中开始会话。",
  openProject: "打开项目",
  fatalErrorTitle: "无法启动 Premire",
  fatalErrorHint: "在 Premire 旁边的 .env 文件、~/.premire/config 或环境变量中设置 PREMIRE_API_KEY。",
  loadingText: "Premire 正在加载…",
  noSessions: "暂无会话",
  untitled: "无标题",
  deleteSession: "删除会话",
  selectModel: "选择模型：",
  revertToMessage: "恢复到该消息",
  copy: "复制",
  completed: "已完成",
  diff: "差异",
  regenerate: "重新生成",
  reading: "读取中",
  read: "已读取",
  failedWrite: "写入失败",
  writing: "写入中",
  written: "已创建",
  failedEdit: "编辑失败",
  editing: "编辑中",
  edited: "已编辑",
  listing: "列出中",
  listed: "已列出",
  searchingCodebase: "代码库搜索中",
  searchedCodebase: "Search in codebase",
  running: "运行中",
  ran: "已运行",
  tool: "工具",
  newFile: "新建文件",
  newFolder: "新建文件夹",
  rename: "重命名",
  cut: "剪切",
  paste: "粘贴",
  delete: "删除",
  deleteConfirm: "删除 {name}？",
  createFailed: "创建失败：{error}",
  renameFailed: "重命名失败：{error}",
  newFileTooltip: "新建文件",
  newFolderTooltip: "新建文件夹",
  refreshTooltip: "刷新",
  collapseAllTooltip: "全部折叠",
  loading: "加载中…",
  closeProject: "关闭项目",
  openProjectMenuItem: "打开项目",
  revealExplorer: "在文件管理器中显示",
  removeFromList: "从列表中移除",
  openFolder: "打开文件夹",
  settings: "设置",
  stop: "停止",
  runCommand: "运行命令",
  sendMessage: "发送消息",
  dropFilesAttach: "拖放文件以附加",
  remove: "移除",
  attachFiles: "附加文件",
  cancel: "取消",
  processing: "处理中...",
  vibeAnything: "输入一些内容...",
  selectModelFallback: "选择模型",
  searchModelPlaceholder: "搜索模型...",
  addProvider: "添加提供商",
  configureModels: "配置模型",
  noModelsFound: "未找到模型",
  noModelsEnabled: "没有启用的模型",
  searching: "搜索中…",
  noMatches: "无匹配",
  terminal: "终端",
  search: "搜索",
  terminalTab: "终端 {num}",
  closeTab: "关闭标签页",
  newTerminal: "新建终端",
  shellExited: "[shell 以代码 {code} 退出]",
  cannotOpenFile: "无法打开文件",
  retry: "重试",
  openFileFromTree: "从文件树打开文件",
  unsavedChanges: "未保存的更改",
  closeFile: "关闭 {filename}",
  filePath: "文件路径",
  selectFileToEdit: "选择要编辑的文件",
  copyCode: "复制",
  openSettingsHotkey: "打开设置",
  clearChatHotkey: "清除聊天",
  manuallyStopped: "已由用户停止",

  // MCP
  edit: "编辑",
  mcpServers: "MCP 服务器",
  mcpServersCount: "MCP 服务器 ({count})",
  mcpRefreshStatuses: "刷新状态",
  mcpNoServersConfigured: "未配置 MCP 服务器",
  mcpOpenSettings: "打开 MCP 设置",
  mcpAddServer: "添加服务器",
  mcpVisualEditor: "编辑器",
  mcpRawConfig: "Raw 配置",
  mcpExport: "导出",
  mcpImport: "导入",
  mcpSaveTomlConfig: "保存 TOML 配置",
  mcpEnableServer: "启用服务器",
  mcpDisableServer: "禁用服务器",
  mcpStartServer: "启动服务器",
  mcpStopServer: "停止服务器",
  mcpAddServerTitle: "添加 MCP 服务器",
  mcpEditServerTitle: "编辑 MCP 服务器",
  mcpServerName: "服务器名称",
  mcpCommandPath: "命令（可执行文件路径）",
  mcpCommandPlaceholder: "npx、uvx 或 /path/to/binary",
  mcpArguments: "参数（空格分隔）",
  mcpEnvVariables: "环境变量",
  mcpEnvKeyPlaceholder: "键",
  mcpEnvValuePlaceholder: "值",
  mcpAddEnvVar: "+ 添加环境变量",
  mcpEnableOnStartup: "启动时启用",
  mcpSaveServer: "保存服务器",
  mcpDeleteConfirm: "确定要删除 MCP 服务器“{name}”吗？",
  mcpServerNameRequired: "服务器名称为必填项。",
  mcpServerCommandRequired: "服务器命令为必填项。",
  mcpServerExists: "已存在同名服务器。",
  mcpSaveFailed: "保存失败: {error}",
  mcpInvalidJsonFormat: "MCP 配置 JSON 格式无效",
  mcpFailedParseJson: "无法解析导入的 JSON",
  mcpInvalidConfigFormat: "配置格式无效: {error}",

  // GitCommitTooltip
  commitFileChanged_one: "1 个文件已更改",
  commitFileChanged_few: "{count} 个文件已更改",
  commitFileChanged: "{count} 个文件已更改",
  commitInsertion_one: "1 行插入(+)",
  commitInsertion_few: "{count} 行插入(+)",
  commitInsertion: "{count} 行插入(+)",
  commitDeletion_one: "1 行删除(-)",
  commitDeletion_few: "{count} 行删除(-)",
  commitDeletion: "{count} 行删除(-)",
  openCommit: "打开提交",
  copyCommitHash: "复制提交哈希",
  openOnGitHub: "在 GitHub 上打开",
  noFilesChanged: "没有更改的文件",
  inlineGenerating: "正在生成代码...",
  inlineEditCode: "请求 Inline Vibe 编辑代码...",
  inlineRefineCode: "请求 Inline Vibe 再次优化/编辑...",
  inlineSend: "发送 (Ctrl+Enter)",
  inlineAccept: "接受更改",
  inlineReject: "拒绝",
  inlinePrevDiff: "上一个差异",
  inlineNextDiff: "下一个差异",
  videoPlay: "播放 (Space)",
  videoPause: "暂停 (Space)",
  videoMute: "静音 (M)",
  videoUnmute: "取消静音 (M)",
  videoVolume: "音量",
  videoPlaybackSpeed: "播放速度",
  videoFullscreen: "全屏 (F)",
  failedReadFile: "读取文件失败",
  baseUrlPlaceholder: "https://api.example.com/v1",
  iconUrlPlaceholder: "https://example.com/icon.svg",
  modelsUrlPlaceholder: "https://api.example.com/v1/models",
  copyMessage: "复制",
  regenerateMessage: "重新生成",

  // Source control
  sourceControl: "源代码控制",
  viewAsFlatList: "查看平面列表",
  viewsAndMoreActions: "视图和更多操作...",
  stageAllChanges: "暂存所有变更",
  checkoutCreateBranch: "结帐/创建分支...",
  refreshStatus: "刷新状态",
  repositories: "存储库",
  commitMessagePlaceholder: "消息（Ctrl+Enter 以在“{branch}”上提交）",
  commitBtn: "犯罪",
  filterChangesPlaceholder: "过滤器更改（例如 *.ts、src/）",
  clearFilter: "清除过滤器",
  noChangesDetected: "在存储库中未检测到任何更改。",
  stagedChanges: "阶段性改变",
  unstageAll: "全部取消暂存",
  unstageChanges: "取消暂存更改",
  discardChanges: "放弃更改",
  stageChanges: "阶段变化",
  graph: "图形",
  noCommitsInGraph: "图表历史记录中没有提交。",
  newBranchName: "新的分行名称...",
  createBranchBtn: "创造",
  currentBranch: "（当前的）",

  // Auto-added translated keys
  renderFileTree: "美丽的文件树",
  renderFileTreeDesc: "将文件夹结构渲染为漂亮的 UI 组件而不是原始文本",
  apiKeyPlaceholder: "API密钥",
  customIcon: "自定义图标（URL 或上传）",
  modelsUrl: "型号列表 URL（可选）",
  headers: "标头",
  parameters: "参数",
  headerKey: "标头名称",
  headerValue: "标头值",
  paramKey: "参数名称",
  paramValue: "参数值",
  uploadIcon: "上传图标",
  closeTerminal: "关闭终端",
  hideButton: "隐藏",
  showButton: "展示",
  restoreButtons: "恢复按钮",
  filesChanged: "{count} 个文件已更改",
  filesChanged_one: "{count} 个文件已更改",
  filesChanged_few: "{count} 个文件已更改",
  changes: "变化",
  exploring: "探索",
  explored: "探索",
  editProject: "编辑",
  editProjectTitle: "编辑项目",
  projectIcon: "图标",
  backgroundColor: "背景颜色",
  closeFromList: "关闭",
  searchInCode: "在代码中搜索",
  searchInCodePlaceholder: "搜索",
  replacePlaceholder: "代替",
  refreshSearch: "刷新搜索",
  clearSearchResults: "清除搜索结果",
  viewAsTree: "以树形式查看",
  showReplace: "显示替换",
  hideReplace: "隐藏替换",
  matchCase: "火柴盒",
  matchWholeWord: "匹配整个单词",
  useRegex: "使用正则表达式",
  preserveCase: "保存箱",
  replaceAll: "全部替换",
  filesToIncludeExclude: "要包含/排除的文件",
  filesToInclude: "要包含的文件",
  filesToExclude: "要排除的文件",
  includePlaceholder: "例如*.ts，src/**",
  excludePlaceholder: "例如节点模块，*.test.ts",
  noResultsFound: "没有找到结果。",
  searchInCodeResults_one: "{count} 个结果位于 {fileCount} 个文件中",
  searchInCodeResults_few: "{count} 个结果产生 {fileCount} 个文件",
  searchInCodeResults: "{count} 个结果产生 {fileCount} 个文件",
  typeToSearch: "输入搜索查询以按内容查找文件。",
  loadingMatches: "加载中...",
  moreMatches_one: "… 还有 {count} 条匹配项",
  moreMatches_few: "…还有 {count} 场比赛",
  moreMatches: "…还有 {count} 场比赛",
  newProjectHotkey: "新项目",
  closeProjectHotkey: "关闭项目",
  closeFileHotkey: "关闭文件",
  navigation: "导航",
  chat: "聊天",
  workspace: "工作空间",
  project: "项目",
  editor: "编辑",
  noHotkeys: "没有加载热键",
  design: "设计",
  animations: "动画",
  animStyleFade: "褪色",
  animStyleSlide: "滑动",
  animStyleScale: "规模",
  animStyleFadeSlide: "淡入淡出 + 滑动",
  animStyleNone: "无动画",
  animProjectHover: "项目悬停",
  animProjectHoverDesc: "将鼠标悬停在项目图块上时的动画",
  animProjectSwitch: "项目切换",
  animProjectSwitchDesc: "打开新项目时的过渡",
  animSidebarSlide: "侧边栏",
  animSidebarSlideDesc: "打开/关闭侧面板",
  animContextMenu: "上下文菜单",
  animContextMenuDesc: "上下文菜单外观",
  animButtons: "按钮",
  animButtonsDesc: "悬停时的交互元素",
  animPanelAppear: "面板和模态框",
  animPanelAppearDesc: "设置、弹出窗口和模式外观",
  animMultiplier: "动画流畅度",
  animMultiplierDesc:
    "Animation smoothness multiplier. 0 = stopped, 0.5 = snappy, 1 = normal, 2 = smooth, 5 = ultra smooth",
  windowEffects: "窗口效果",
  blurOverlay: "背景模糊",
  blurOverlayDesc: "模糊模式窗口后面的内容（设置、上下文菜单）",
  blurNone: "没有任何",
  blurSubtle: "微妙的",
  blurStrong: "强的",
  borderRadius: "边界半径",
  borderRadiusDesc: "UI 元素的圆角",
  uiZoom: "用户界面缩放",
  zoomStep: "变焦步长",
  zoomStepDesc: "每次按 Ctrl+加号/Ctrl+减号可改变缩放级别多少",
  zoomDefault: "默认缩放",
  zoomDefaultDesc: "按 Ctrl+0 时的缩放级别",
  appName: "Premire 桌面",
  appVersion: "v1.3.9",
  shell: "壳",
  langRussian: "俄语",
  langEnglish: "英语",
  langChinese: "中文 (繁体)",
  langChineseSimplified: "简体中文",
  langUkrainian: "乌克兰",
  langBelarusian: "白俄罗斯语",
  langSpanish: "西班牙语",
  langItalian: "意大利语",
  langPortuguese: "葡萄牙语",
  langJapanese: "日本人",
  langSerbian: "塞尔维亚",
  langFrench: "法语",
  langGerman: "德语",
  langHindi: "印地语",
  langArabic: "阿拉伯",
  langIndonesian: "印度尼西亚",
  langKorean: "韩国人",
  langTurkish: "土耳其",
  langVietnamese: "越南语",
  langPolish: "抛光",
  langDutch: "荷兰语",
  langRomanian: "罗马尼亚语",
  langGreek: "希腊语",
  langSwedish: "瑞典",
  langKazakh: "哈萨克语",
  langAzerbaijani: "阿塞拜疆语",
  langThai: "泰国",
  langBengali: "孟加拉",
  langPunjabi: "旁遮普语",
  langBulgarian: "保加利亚语",
  langCzech: "捷克语",
  langFilipino: "菲律宾人",
  langPersian: "波斯语",
  langMalay: "马来语",
  langBurmese: "缅甸语",
  langAmharic: "阿姆哈拉语",
  langMarathi: "马拉地语",
  codeTab: "代码",
  editorFontSize: "字体大小",
  editorFontSizeDesc: "编辑器和终端字体大小",
  editorLineHeight: "行高",
  editorLineHeightDesc: "编辑器行高乘数",
  editorLigatures: "字体连字",
  editorLigaturesDesc: "启用编码连字（例如 =>、===）",
  editorCursorStyle: "光标样式",
  editorCursorStyleDesc: "编辑器光标的形状",
  editorCursorBlink: "光标闪烁",
  editorCursorBlinkDesc: "光标动画样式",
  cursorLine: "线",
  cursorBlock: "堵塞",
  cursorUnderline: "强调",
  cursorLineThin: "细线",
  cursorBlockOutline: "块轮廓",
  cursorUnderlineThin: "下划线细",
  blinkBlink: "眨",
  blinkSmooth: "光滑的",
  blinkPhase: "阶段",
  blinkExpand: "扩张",
  blinkSolid: "坚硬的",
  manageThemes: "管理主题",
  manageThemesDesc: "导入或导出您的颜色主题",
  importTheme: "进口",
  exportTheme: "出口",
  borderStyle: "边框样式",
  borderStyleDesc: "打开或关闭面板边框",
  borderStyleBordered: "有边框",
  borderStyleBorderless: "无边框",
  hideSourceControl: "隐藏源代码管理",
  showSourceControl: "显示源代码控制",

  // Newly added UI strings
  backBtn: "后退",
  onboardingStepSettingsTitle: "工作区设置",
  continueBtn: "继续",
  welcomeThanks: "让我们为您的工作流程设置 Premire。",
  startVibingBtn: "完成设置",
  rerunOnboarding: "运行安装向导",
  onboardingStepThemeTitle: "选择一个主题",
  letsVibeBtn: "让我们来感受一下",
  animationSpeed: "动画速度",
  onboardingStepSettingsDesc: "立即设置您的首选项或稍后更改它们。",
  onboardingStepAnimationDesc: "选择界面元素的过渡样式并调整其平滑度。",
  useRegionalProxy: "使用区域代理（欧洲）",
  welcomeGreeting: "你好，{name}",
  rerunOnboardingDesc: "重新触发初始欢迎屏幕和快速入门向导",
  useRegionalProxyDesc: "通过欧洲的快速代理服务器路由 API 请求以绕过区域限制",
  onboardingStepThemeDesc: "在继续之前预览主题。",
  onboardingStepAnimationTitle: "动画设置",
  animationSpeedDesc: "界面过渡和平滑效果缩放",
  activityFetchUrl: "正在获取网页 {url}",
  activityFetchUrlGeneral: "正在获取网页",
  activityGitBranches: "查看 Git 分支",
  activityGitCommand: "Git操作：{命令}",
  activityGitDiff: "检查 Git 差异",
  activityGitLog: "查看Git提交日志",
  activityGitStatus: "检查 Git 状态",
  activityGroupAgent: "调查",
  activityGroupAgentN: "调查 — {count} 项任务",
  activityGroupAgentN_few: "Исследование — {count} задачи",
  activityGroupAgentN_one: "调查 — {count} 项任务",
  activityGroupBrowse: "浏览文件夹",
  activityGroupBrowseN: "正在浏览 {count} 个文件夹",
  activityGroupBrowseN_few: "Просмотр {count} папок",
  activityGroupBrowseN_one: "正在浏览 {count} 个文件夹",
  activityGroupCommand: "运行命令",
  activityGroupCommandN: "运行 {count} 个命令",
  activityGroupCommandN_few: "Выполнение {count} команд",
  activityGroupCommandN_one: "运行 {count} 命令",
  activityGroupEdit: "编辑过的文件",
  activityGroupEditN: "编辑 {count} 个文件",
  activityGroupEditN_few: "Редактирование {count} файлов",
  activityGroupEditN_one: "正在编辑 {count} 个文件",
  activityGroupExternal: "外部工具",
  activityGroupExternalN: "外部工具 — {count} 次调用",
  activityGroupExternalN_few: "Внешние инструменты — {count} вызова",
  activityGroupExternalN_one: "外部工具 — {count} 调用",
  activityGroupGit: "Git操作",
  activityGroupGitN: "Git — {count} 次操作",
  activityGroupGitN_few: "Git — {count} операции",
  activityGroupGitN_one: "Git — {count} 操作",
  activityGroupRead: "读取文件",
  activityGroupReadN: "正在读取 {count} 个文件",
  activityGroupReadN_few: "Чтение {count} файлов",
  activityGroupReadN_one: "正在读取 {count} 个文件",
  activityGroupSearch: "搜索",
  activityGroupSearchN: "搜索 — {count} 条查询",
  activityGroupSearchN_few: "Поиск — {count} запроса",
  activityGroupSearchN_one: "搜索 — {count} 条查询",
  activityGroupTodo: "任务规划",
  activityGroupTodoN: "计划 — {count} 项任务",
  activityGroupTodoN_few: "Планирование — {count} задачи",
  activityGroupTodoN_one: "计划 — {count} 项任务",

  // Agent flow (linear run redesign)
  flowThinking: "思考中…",
  flowThought: "思考过程",
  flowAnalysis: "分析",
  flowCountRead: "{count} 次读取",
  flowCountSearch: "{count} 次搜索",
  flowCountBrowse: "{count} 次浏览目录",
  flowCountWeb: "{count} 次网络搜索",
  flowCountGit: "{count} 次 git 操作",
  activityGroupTools: "行动",
  activityGroupToolsN: "{count} 次操作",
  activityGroupToolsN_few: "{count} действия",
  activityGroupToolsN_one: "{count} 个操作",
  activityGroupWeb: "网络搜索",
  activityGroupWebN: "网络搜索 — {count} 条查询",
  activityGroupWebN_few: "Веб-поиск — {count} запроса",
  activityGroupWebN_one: "网络搜索 — {count} 条查询",
  activityInspectFolder: "探索{名称}",
  activityInvestigateTask: "调查任务",
  activityProjectStructure: "探索项目结构",
  activityReadCode: "检查代码",
  activityReadFile: "正在审核{name}",
  activityRepeatedCalls: "{count} 次通话",
  activityRunCommand: "检查项目",
  activitySearchCode: "寻找相关实现",
  activitySearchQuery: "搜索“{query}”",
  activityUpdateCode: "更新代码",
  activityUpdateFile: "正在更新{名称}",
  activityUseTool: "正在运行{名称}",
  activityWebSearch: "在网络上搜索“{query}”",
  activityWebSearchGeneral: "在网络上搜索信息",
  addModel: "添加型号",
  agentRunMinutesShort: "{计数}米",
  agentRunSeconds: "{count} 秒",
  agentRunSecondsShort: "{count} 个",
  agentRunSeconds_few: "{count} 秒",
  agentRunSeconds_one: "{count} 秒",
  agentRunWorkedFor: "工作了{时间}",
  agentRunWorkingFor: "工作{时间}",
  copyFormatted: "复制文本",
  copyRaw: "复制为原始文件",
  customModelsLabel: "型号",
  errorNoticeBlockedTitle: "提供商访问受到限制",
  errorNoticeNetworkTitle: "无法联系服务",
  errorNoticeProviderTitle: "提供者返回错误",
  errorNoticeQuotaTitle: "已达到提供商限制",
  experimentalExtremeRadius: "实验极限半径（最大 100px）",
  experimentalExtremeRadiusDesc: "允许将 UI 边框半径设置为最大 100 像素。实验旗帜！",
  fetchedUrl: "获取的网址",
  fetchingUrl: "正在获取网址",
  generateCommitMessage: "使用 AI 生成提交消息",
  gitBlame: "分析线路作者身份",
  gitBlameDone: "分析线路作者",
  gitBranches: "检查分支机构",
  gitBranchesDone: "检查分行",
  gitDiff: "审查变更",
  gitDiffDone: "已审核变更",
  gitInspect: "检查 Git 历史记录",
  gitInspectDone: "检查 Git 历史记录",
  gitLog: "审查提交",
  gitLogDone: "已审查的提交",
  gitRefs: "检查 Git 引用",
  gitRefsDone: "检查了 Git 参考",
  gitShow: "检查 Git 对象",
  gitShowDone: "检查的 Git 对象",
  gitStatus: "检查状态",
  gitStatusDone: "检查状态",
  hideToolCalls: "隐藏工具调用",
  modelDisplayName: "显示名称",
  modelIdPlaceholder: "型号 ID",
  promptMarkdown: "提示输入中的 Markdown",
  promptMarkdownDesc: "在输入提示时实时渲染 Markdown 格式",
  promptMarkdownGhost: "显示语法标记 (**)",
  promptMarkdownGhostDesc: "在格式化文本内显示灰色语法字符（**、`、#）",
  reasoningEffortHigh: "高的",
  reasoningEffortLow: "低的",
  reasoningEffortMedium: "中等的",
    reasoningEffortCustom: "自定义预算",
  reasoningEffortTokens: "Token",
  reasoningNotSupported: "此模型不支持推理",
  reasoningEffortNone: "没有任何",
  searchedWeb: "网页搜索",
  searchingWeb: "搜索网页",
  showToolCalls: "显示工具调用",
  tabStyle: "选项卡样式",
  tabStyleDefault: "默认",
  tabStyleDesc: "用于编辑器选项卡的方形或圆形药丸",
  tabStylePills: "药丸",
  todoBlocked: "任务被阻止",
  todoCompleted: "已完成任务",
  todoCount: "{已完成}，共 {count} 个",
  todoCreated: "已创建任务计划",
  todoPin: "固定任务列表",
  todoProgress: "已完成的任务：{completed}（共 {count}）",
  todoTitle: "任务",
  todoUnpin: "取消固定任务列表",
  // Settings Section Blocks
  settingsBlockEnv: "Environment & Localization",
  settingsBlockEnvDesc: "Display language, command shell, and network routing",
  settingsBlockAi: "AI Intelligence & Autonomy",
  settingsBlockAiDesc: "Agent autonomous permissions and reasoning process",
  settingsBlockChat: "Chat & Workspace View",
  settingsBlockChatDesc: "Markdown rendering and interactive project file tree",
  settingsBlockSoundDesc: "Audio cues when generation finishes or stops",
  settingsBlockOnboarding: "Initial Setup Wizard",
  settingsBlockOnboardingDesc: "Re-run the initial Premire tour and environment setup",
  settingsBlockTypography: "Editor Typography & Fonts",
  settingsBlockTypographyDesc: "Character sizing, line height, and code ligatures",
  settingsBlockCursor: "Cursor & Typing Dynamics",
  settingsBlockCursorDesc: "Cursor style and blinking behavior while editing",
  settingsBlockTheme: "Color Scheme & Diff Preview",
  settingsBlockThemeDesc: "Light, dark, or system mode and interactive code diff preview",
  settingsBlockPanels: "Panel Geometry & Styling",
  settingsBlockPanelsDesc: "Corner rounding, border appearance, and tab style",
  settingsBlockScaling: "Workspace Scaling",
  settingsBlockScalingDesc: "Font size and interface proportions of the workspace",
  settingsBlockAnimations: "Animation Dynamics & Effects",
  settingsBlockAnimationsDesc: "Interactive feedback, project switching, and transition timing",
  diffOriginal: "Original",
  diffModified: "Premire 2.0",
  diffRemovedLines: "-3 lines",
  diffAddedLines: "+4 lines",
  animPreviewWindow: "Window",
  animPreviewSidebar: "Sidebar",
  animPreviewMenu: "Menu",
  animPreviewButtons: "Buttons",
  animPreviewPlay: "Play",
  animPreviewDialogTitle: "Confirm Action",
  animPreviewDialogMsg: "Save project changes before building?",
  animPreviewSave: "Save",
  animPreviewCancel: "Cancel",
  animPreviewNewFile: "New File",
  animPreviewNewFolder: "New Folder",
  animPreviewDelete: "Delete",
  animPreviewRunTask: "Run Task",
  // Project dialogs
  newProject: "新建项目",
  projectName: "项目名称",
  create: "创建",
  creating: "正在创建...",
  renameProject: "重命名项目",
  saving: "正在保存...",

  // Additional UI & Navigation translations
  providerSettingsTabs: "提供商设置",
  providerGeneralTab: "常规",
  providerAdvancedTab: "高级",
  todoStep: "步骤 {stepNumber} / {stepCount}",
  todoFilesChanged: "已更改 {count} 个文件",
  todoFilesChanged_one: "已更改 {count} 个文件",
  todoFilesChanged_few: "已更改 {count} 个文件",
  messagesReverted: "已撤回 {count} 条消息",
  messagesReverted_one: "已撤回 {count} 条消息",
  changedFilesTitle: "已更改的文件",
  restore: "恢复",
  subagentReadOnly: "此处不支持输入。",
  goBack: "返回",
  loadingDiff: "正在加载差异：",
  showMore: "显示更多...",
  emptyDirectory: "空目录。",
  promptSuggestionStart: "从哪里开始？",
  promptSuggestionWorkspace: "在当前项目中我们接下来做什么？",
  promptSuggestionCode: "有哪段代码需要深入分析吗？",
  promptSuggestionEntry: "要检查此应用程序的入口点吗？",
  promptSuggestionBlocker: "当前遇到了什么阻碍？",
  promptSuggestionStructure: "需要梳理此代码仓库的结构吗？",
  promptSuggestionNext: "寻找瓶颈还是确定下一步？",
  reasoningEffortMinimal: "最低",
  reasoningEffortXhigh: "极高",
  reasoningEffortMax: "最大",
  reasoningEffortUltra: "终极",
  composerOptions: "编写器选项",
  composerModel: "模型",
  composerEffort: "思考程度",
  composerPermissionAsk: "请求批准",
  composerPermissionAskDesc: "修改外部文件及访问网络前始终询问",
  composerPermissionConfirm: "替我批准",
  composerPermissionConfirmDesc: "仅对检测到潜在不安全的操作进行询问",
  composerPermissionFull: "完全访问",
  composerPermissionFullDesc: "无限制访问网络及计算机上的任何文件",
  composerPermissionAuto: "自动",
  composerPermissionMenu: "权限模式",
  composerPermissionAutoDesc: "自动允许智能体操作",
  composerPermissionTitle: "如何确认智能体的操作？",
  composerPermissionFullConfirmTitle: "开启完全访问？",
  composerPermissionFullConfirmDesc: "智能体将获得以下功能的无限制访问权限：",
  composerPermissionFullFiles: "文件和文件夹",
  composerPermissionFullFilesDesc: "读取、修改和删除计算机上的文件",
  composerPermissionFullTerminal: "终端命令",
  composerPermissionFullTerminalDesc: "使用系统权限执行命令",
  composerPermissionFullInternet: "网络与已连接的应用",
  composerPermissionFullInternetDesc: "访问网站和已连接的服务",
  composerPermissionFullRisk: "完全访问允许智能体执行潜在危险的操作。",
  composerPermissionFullConfirm: "确认开启",
  composerPermissionSettings: "权限设置",
  mcpConfiguration: "配置",
  mcpCommand: "命令",
  mcpArgumentsShort: "参数",
  mcpStatusRunning: "已连接",
  mcpStatusStarting: "正在启动",
  mcpStatusStopped: "已停止",
  mcpStatusError: "需要注意",
  mcpStatusDisabled: "已禁用",
  activitySummaryRead: "读取了文件",
  activitySummaryEdit: "编辑了文件",
  activitySummaryCommand: "执行了命令",
  activitySummaryGit: "检查了 Git",
  activitySummaryWeb: "进行了网络搜索",
  activitySummaryAgent: "分析了任务",
  activitySummaryExternal: "使用了外部工具",
  activitySummaryTools: "使用了工具",
  activitySummaryAnd: "及",
  reasoningThinking: "思考中…",
  reasoningThought: "已思考",
  reasoningForSeconds: "{seconds} 秒",
  reasoningForFewSeconds: "几秒钟",
  exploreLabel: "浏览",
  flowCountRead_one: "{count} 次读取",
  flowCountRead_few: "{count} 次读取",
  flowCountSearch_one: "{count} 次搜索",
  flowCountSearch_few: "{count} 次搜索",
  flowCountBrowse_one: "{count} 次文件夹浏览",
  flowCountBrowse_few: "{count} 次文件夹浏览",
  flowCountWeb_one: "{count} 次网络搜索",
  flowCountWeb_few: "{count} 次网络搜索",
  flowCountGit_one: "{count} 次 Git 操作",
  flowCountGit_few: "{count} 次 Git 操作",
  appearanceLightTheme: "浅色主题",
  appearanceDarkTheme: "深色主题",
  appearanceAccent: "强调色",
  appearanceForeground: "前景色",
  appearancePreferences: "界面偏好",
  newConversation: "新对话",
  searchSessions: "搜索对话",
  searchSessionsPlaceholder: "搜索对话和项目",
  searchResults: "搜索结果",
  noMatchingSessions: "未找到匹配的对话",
  recentSessions: "最近",
  pinnedSessions: "已固定",
  sidebarNavigation: "对话导航",
  projects: "项目",
  addProject: "打开文件夹 / 项目",
  noProjects: "暂无项目",
  newChatInProject: "在项目中新建对话",
  projectOptions: "项目选项",
  sessionOptions: "对话选项",
  renameSession: "重命名对话",
  copySessionId: "复制对话 ID",
  loadingSessions: "正在加载对话",
  showAllProjects: "显示所有项目 ({count})",
  showAllSessions: "显示所有对话 ({count})",
  allProjects: "所有项目",
  today: "今天",
  yesterday: "昨天",
  last7Days: "最近 7 天",
  last30Days: "最近 30 天",
  older: "更早",
  noScheduledTasks: "暂无计划任务",
  noScheduledTasksDesc: "配置后，后台计划任务和定时器将显示在此处。",
  createScheduledTask: "创建任务",
  openProjectFolder: "在文件管理器中显示",
  deleteSessionConfirm: "删除此对话？",
  showAll: "显示全部",
  showLess: "收起",
  emptyWorkspaceTitle: "在 {project} 中创建什么？",
  emptyWorkspaceExplore: "浏览代码并了解其结构",
  emptyWorkspaceBuild: "创建新功能或工具",
  emptyWorkspaceReview: "审查代码并提出改进建议",
  emptyWorkspaceFix: "查找并修复问题",
  localWorkspace: "本地",
  openPanelTitle: "打开面板",
  openPanelDescription: "选择在此侧面板中打开的工作区视图。",
  filesTitle: "文件",
  searchFilesPlaceholder: "搜索文件",
  searchingFiles: "正在搜索文件…",
  noMatchingFiles: "未找到匹配的文件",
  searchFilesFailed: "搜索文件失败：{error}",
  searchTitle: "搜索",
  gitTitle: "Git",
  terminalTitle: "终端",
  browserTitle: "浏览器",
  browserTabs: "浏览器标签页",
  browserNewTab: "新建标签页",
  browserBack: "后退",
  browserForward: "前进",
  browserReload: "刷新",
  browserAddress: "地址",
  browserAddressPlaceholder: "输入网址 (URL)",
  browserLoading: "加载中",
  browserStarting: "正在启动隔离的 Chromium…",
  browserEmpty: "输入网址以打开网页",
  browserTakeControl: "手动操作",
  browserReturnAgent: "结束手动操作",
  browserManualActive: "手动控制中",
  browserActivityOpen: "正在打开 {target}",
  browserActivityNavigate: "正在跳转到 {target}",
  browserActivityClick: "正在点击 “{target}”",
  browserActivityFill: "正在在 “{target}” 中输入文本",
  browserActivityVerify: "正在验证结果",
  browserSummaryOpened: "打开了网页",
  browserSummaryActions_one: "执行了 {count} 个操作",
  browserSummaryActions_few: "执行了 {count} 个操作",
  browserSummaryActions: "执行了 {count} 个操作",
  browserSummaryVerified: "已验证结果",
  browserDetailUrl: "URL",
  browserDetailAction: "操作",
  browserDetailTarget: "目标",
  browserDetailDuration: "耗时",
  browserDetailResult: "结果",
  listSkillsActive: "正在检查可用技能",
  listSkillsDone: "已获取可用技能列表",
  readSkillActive: "正在连接到技能 {name}",
  readSkillDone: "已加载技能 {name} 的说明",
  readSkillResourceActive: "正在读取技能 {name} 的资源",
  readSkillResourceDone: "已读取技能 {name} 的资源",
  activityGroupSkills: "技能",
  activityGroupSkillsN_one: "{count} 个技能",
  activityGroupSkillsN_few: "{count} 个技能",
  activityGroupSkillsN: "{count} 个技能",
  activitySummarySkills: "已加载技能",
  activitySummaryBrowser: "操作了浏览器",
  serversTitle: "服务器",
  settingsTitle: "设置",
  keybindingsTitle: "快捷键",
  untitledSession: "无标题对话",
  panels: "面板",
  files: "文件",
  failedToLoadDiff: "无法加载差异",
  groupBy: "分组",
  groupByProject: "按项目",
  groupByNone: "不分组",
  sortConversations: "排序对话",
  sortByLastUpdated: "最后更新",
  sortByAlphabetical: "按字母顺序",
  sortByDateAdded: "按创建日期",
  showSubtitles: "显示副标题",
  showArchived: "显示已归档",
  terminalModeLabel: "终端模式",
  exitTerminalMode: "退出终端模式",
  copyPath: "复制路径",
  copyRelativePath: "复制相对路径",
  animFade: "淡入淡出",
  animSlide: "滑动",
  animScale: "缩放",
  animFadeSlide: "淡入与滑动",
  animNone: "无动画",
};
