import type { ShortcutCategory } from "@/platform/keybinding/browser/useKeybindings";
import type { LangCode } from "@/platform/localization/localizationCatalog";

export interface CategoryTranslation {
  title: string;
  short: string;
}

export interface HotkeysLocale {
  all: string;
  categoriesLabel: string;
  searchPlaceholder: string;
  commandsConfigured: (count: number) => string;
  statsText: (matched: number, total: number) => string;
  pressCombo: string;
  cancelEsc: string;
  rebindTooltip: string;
  resetTooltip: string;
  footerTip: string;
  emptyTitle: string;
  emptyDesc: string;
  resetFilters: string;
  unassigned: string;
  chordThen: string;
  categories: Record<ShortcutCategory, CategoryTranslation>;
  commands: Record<string, string>;
}

// Updated with extended bindings
const RU_LOCALE: HotkeysLocale = {
  all: "Все",
  categoriesLabel: "Разделы",
  searchPlaceholder: "Поиск комбинаций по названию команды, клавише или разделу...",
  commandsConfigured: (count: number) => {
    const mod10 = count % 10;
    const mod100 = count % 100;
    if (mod10 === 1 && mod100 !== 11) return `${count} команда настроена`;
    if (mod10 >= 2 && mod10 <= 4 && (mod100 < 10 || mod100 >= 20)) return `${count} команды настроено`;
    return `${count} команд настроено`;
  },
  statsText: (matched, total) => (matched === total ? `${total} комбинаций` : `Найдено ${matched} из ${total}`),
  pressCombo: "Нажмите комбинацию клавиш... (Esc для отмены)",
  cancelEsc: "Нажмите Esc для отмены",
  rebindTooltip: "Нажмите, чтобы переназначить клавишу",
  resetTooltip: "Сбросить на значение по умолчанию",
  footerTip: "Нажмите на любую комбинацию клавиш, чтобы переназначить её. Нажмите Escape для отмены записи или кнопку сброса для возврата к настройкам по умолчанию.",
  emptyTitle: "Комбинации не найдены",
  emptyDesc: "Попробуйте изменить поисковый запрос или выбрать другой раздел.",
  resetFilters: "Сбросить фильтры",
  unassigned: "Не назначено",
  chordThen: "затем",
  categories: {
    navigation: { title: "Навигация и вкладки", short: "Навигация" },
    search: { title: "Поиск и файлы", short: "Поиск" },
    chat: { title: "Чат и ИИ-помощник", short: "Чат" },
    workspace: { title: "Рабочая область и интерфейс", short: "Окружение" },
    terminal: { title: "Встроенный терминал", short: "Терминал" },
    project: { title: "Проекты и папки", short: "Проекты" },
    editor: { title: "Редактор и файлы кода", short: "Редактор" },
  },
  commands: {
    "open-settings": "Открыть настройки",
    "quick-search": "Быстрый переход к файлу",
    "open-search-in-code": "Поиск по всему коду",
    "search-toggle-match-case": "Поиск: Учитывать регистр",
    "search-toggle-whole-word": "Поиск: Слова целиком",
    "search-toggle-regex": "Поиск: Регулярные выражения",
    "search-toggle-replace": "Поиск: Панель замены",
    "search-toggle-filters": "Поиск: Фильтры включения/исключения",
    "search-toggle-tree": "Поиск: Древовидный вид",
    "search-refresh": "Поиск: Обновить результаты",
    "search-clear": "Поиск: Очистить поле",
    "focus-input": "Фокус на строке ввода",
    "new-chat": "Создать новый чат",
    "next-chat": "Следующий чат",
    "prev-chat": "Предыдущий чат",
    "clear-chat": "Очистить текущий чат",
    "toggle-chat-side": "Переключить боковую панель чата",
    "toggle-terminal": "Показать/скрыть терминал",
    "toggle-file-tree": "Показать/скрыть проводник файлов",
    "new-terminal": "Открыть новую вкладку терминала",
    "next-terminal": "Следующая вкладка терминала",
    "prev-terminal": "Предыдущая вкладка терминала",
    "close-terminal": "Закрыть вкладку терминала",
    "new-project": "Создать новый проект",
    "close-project": "Закрыть текущий проект",
    "close-file": "Закрыть активный файл",
    "next-file": "Следующий файл вкладки",
    "prev-file": "Предыдущий файл вкладки",
    "save-file": "Сохранить активный файл",
    "save-all-files": "Сохранить все файлы",
    "reopen-closed-tab": "Заново открыть закрытый файл",
    "format-document": "Форматировать документ",
    "toggle-comment": "Переключить комментарий строки",
    "toggle-word-wrap": "Переключить перенос строк",
    "find-in-file": "Найти в текущем файле",
    "replace-in-file": "Заменить в текущем файле",
    "duplicate-line": "Дублировать строку вниз",
    "move-line-up": "Переместить строку вверх",
    "move-line-down": "Переместить строку вниз",
    "toggle-git-panel": "Переключить панель Git",
    "zoom-in": "Увеличить масштаб",
    "zoom-out": "Уменьшить масштаб",
    "zoom-reset": "Сбросить масштаб",
    "open-hotkeys": "Открыть горячие клавиши",
    "open-providers": "Открыть провайдеры моделей",
    "open-mcp": "Открыть серверы MCP",
  },
};

const UK_LOCALE: HotkeysLocale = {
  all: "Всі",
  categoriesLabel: "Розділи",
  searchPlaceholder: "Пошук комбінацій за назвою команди, клавішею або розділом...",
  commandsConfigured: (count: number) => `${count} команд налаштовано`,
  statsText: (matched, total) => (matched === total ? `${total} комбінацій` : `Знайдено ${matched} з ${total}`),
  pressCombo: "Натисніть комбінацію клавіш... (Esc для скасування)",
  cancelEsc: "Натисніть Esc для скасування",
  rebindTooltip: "Натисніть, щоб перепризначити клавішу",
  resetTooltip: "Скинути до значень за замовчуванням",
  footerTip: "Натисніть на будь-яку комбінацію клавіш, щоб перепризначити її. Натисніть Escape для скасування запису або кнопку скидання для повернення до початкових налаштувань.",
  emptyTitle: "Комбінації не знайдено",
  emptyDesc: "Спробуйте змінити пошуковий запит або вибрати інший розділ.",
  resetFilters: "Скинути фільтри",
  unassigned: "Не призначено",
  chordThen: "потім",
  categories: {
    navigation: { title: "Навігація та вкладки", short: "Навігація" },
    search: { title: "Пошук та файли", short: "Пошук" },
    chat: { title: "Чат та ШІ-помічник", short: "Чат" },
    workspace: { title: "Робоча область та інтерфейс", short: "Оточення" },
    terminal: { title: "Вбудований термінал", short: "Термінал" },
    project: { title: "Проєкти та папки", short: "Проєкти" },
    editor: { title: "Редактор та файли коду", short: "Редактор" },
  },
  commands: {
    "open-settings": "Відкрити налаштування",
    "quick-search": "Швидкий перехід до файлу",
    "open-search-in-code": "Пошук по всьому коду",
    "search-toggle-match-case": "Пошук: Враховувати регістр",
    "search-toggle-whole-word": "Пошук: Слова цілком",
    "search-toggle-regex": "Пошук: Регулярні вирази",
    "search-toggle-replace": "Пошук: Панель заміни",
    "search-toggle-filters": "Пошук: Фільтри включення/виключення",
    "search-toggle-tree": "Пошук: Деревоподібний вигляд",
    "search-refresh": "Пошук: Оновити результати",
    "search-clear": "Пошук: Очистити поле",
    "focus-input": "Фокус на рядку введення",
    "new-chat": "Створити новий чат",
    "next-chat": "Наступний чат",
    "prev-chat": "Попередній чат",
    "clear-chat": "Очистити поточний чат",
    "toggle-chat-side": "Перемкнути бічну панель чату",
    "toggle-terminal": "Показати/приховати термінал",
    "toggle-file-tree": "Показати/приховати провідник файлів",
    "new-terminal": "Відкрити нову вкладку термінала",
    "next-terminal": "Наступна вкладка термінала",
    "prev-terminal": "Попередня вкладка термінала",
    "close-terminal": "Закрити вкладку термінала",
    "new-project": "Створити новий проєкт",
    "close-project": "Закрити поточний проєкт",
    "close-file": "Закрити активний файл",
    "next-file": "Наступний файл вкладки",
    "prev-file": "Попередній файл вкладки",
    "save-file": "Зберегти активний файл",
    "save-all-files": "Зберегти всі файли",
    "reopen-closed-tab": "Заново відкрити закритий файл",
    "format-document": "Форматувати документ",
    "toggle-comment": "Перемкнути коментар рядка",
    "toggle-word-wrap": "Перемкнути перенесення рядків",
    "find-in-file": "Знайти у файлі",
    "replace-in-file": "Замінити у файлі",
    "duplicate-line": "Дублювати рядок вниз",
    "move-line-up": "Перемістити рядок вгору",
    "move-line-down": "Перемістити рядок вниз",
    "toggle-git-panel": "Перемкнути панель Git",
    "zoom-in": "Збільшити масштаб",
    "zoom-out": "Зменшити масштаб",
    "zoom-reset": "Скинути масштаб",
    "open-hotkeys": "Відкрити гарячі клавіші",
    "open-providers": "Відкрити провайдери моделей",
    "open-mcp": "Відкрити сервери MCP",
  },
};

const ZH_LOCALE: HotkeysLocale = {
  all: "全部",
  categoriesLabel: "分类",
  searchPlaceholder: "按命令名称、按键或分类搜索快捷键...",
  commandsConfigured: (count: number) => `已配置 ${count} 个命令`,
  statsText: (matched, total) => (matched === total ? `${total} 个快捷键` : `找到 ${matched} / ${total}`),
  pressCombo: "请按下按键组合... (Esc 取消)",
  cancelEsc: "按 Esc 取消",
  rebindTooltip: "点击重新绑定快捷键",
  resetTooltip: "重置为默认快捷键",
  footerTip: "点击任意按键组合即可重新设定。按 Escape 取消录制，或使用重置按钮恢复默认设置。",
  emptyTitle: "未找到匹配的快捷键",
  emptyDesc: "请尝试输入不同的命令名称或选择其他分类。",
  resetFilters: "重置筛选",
  unassigned: "未分配",
  chordThen: "然后",
  categories: {
    navigation: { title: "导航与标签页", short: "导航" },
    search: { title: "搜索与代码查找", short: "搜索" },
    chat: { title: "AI 聊天与提示词", short: "聊天" },
    workspace: { title: "工作区与界面布局", short: "工作区" },
    terminal: { title: "集成终端", short: "终端" },
    project: { title: "项目与文件夹", short: "项目" },
    editor: { title: "编辑器与代码文件", short: "编辑器" },
  },
  commands: {
    "open-settings": "打开设置",
    "quick-search": "快速转到文件",
    "open-search-in-code": "全局代码搜索",
    "focus-input": "聚焦输入框",
    "new-chat": "新建对话",
    "next-chat": "下一个对话",
    "prev-chat": "上一个对话",
    "clear-chat": "清空当前对话",
    "toggle-chat-side": "切换聊天侧边栏",
    "toggle-terminal": "显示/隐藏终端",
    "toggle-file-tree": "显示/隐藏文件资源管理器",
    "new-terminal": "新建终端标签页",
    "next-terminal": "下一个终端标签页",
    "prev-terminal": "上一个终端标签页",
    "close-terminal": "关闭终端标签页",
    "new-project": "新建项目",
    "close-project": "关闭当前项目",
    "close-file": "关闭当前文件",
    "next-file": "下一个文件标签",
    "prev-file": "上一个文件标签",
    "save-file": "Save File",
    "save-all-files": "Save All Files",
    "reopen-closed-tab": "Reopen Closed File",
    "format-document": "Format Document",
    "toggle-comment": "Toggle Line Comment",
    "toggle-word-wrap": "Toggle Word Wrap",
    "find-in-file": "Find in File",
    "replace-in-file": "Replace in File",
    "duplicate-line": "Duplicate Line Down",
    "move-line-up": "Move Line Up",
    "move-line-down": "Move Line Down",
    "toggle-git-panel": "Toggle Source Control (Git)",
    "zoom-in": "Zoom In Interface",
    "zoom-out": "Zoom Out Interface",
    "zoom-reset": "Reset Zoom Interface",
    "open-hotkeys": "Open Keyboard Shortcuts",
    "open-providers": "Open AI Providers",
    "open-mcp": "Open MCP Server Settings",
  },
};

const ES_LOCALE: HotkeysLocale = {
  all: "Todos",
  categoriesLabel: "Categorías",
  searchPlaceholder: "Buscar atajos por comando, tecla o categoría...",
  commandsConfigured: (count: number) => `${count} comandos configurados`,
  statsText: (matched, total) => (matched === total ? `${total} atajos` : `${matched} de ${total}`),
  pressCombo: "Presiona la combinación de teclas... (Esc para cancelar)",
  cancelEsc: "Presiona Esc para cancelar",
  rebindTooltip: "Haz clic para reasignar el atajo",
  resetTooltip: "Restablecer al atajo predeterminado",
  footerTip: "Haz clic en cualquier atajo para reasignarlo. Presiona Escape para cancelar o usa el botón de restablecer para restaurar los valores iniciales.",
  emptyTitle: "No se encontraron atajos",
  emptyDesc: "Prueba buscando con otro nombre o elige una categoría diferente.",
  resetFilters: "Restablecer filtros",
  unassigned: "Sin asignar",
  chordThen: "luego",
  categories: {
    navigation: { title: "Navegación y pestañas", short: "Navegación" },
    search: { title: "Búsqueda y archivos", short: "Búsqueda" },
    chat: { title: "Chat e IA", short: "Chat" },
    workspace: { title: "Espacio de trabajo y diseño", short: "Espacio" },
    terminal: { title: "Terminal integrado", short: "Terminal" },
    project: { title: "Proyectos y carpetas", short: "Proyectos" },
    editor: { title: "Editor y archivos de código", short: "Editor" },
  },
  commands: {
    "open-settings": "Abrir configuración",
    "quick-search": "Ir rápidamente al archivo",
    "open-search-in-code": "Buscar en el código",
    "focus-input": "Enfocar campo de entrada",
    "new-chat": "Nuevo chat",
    "next-chat": "Siguiente chat",
    "prev-chat": "Chat anterior",
    "clear-chat": "Limpiar chat",
    "toggle-chat-side": "Alternar barra lateral de chat",
    "toggle-terminal": "Alternar terminal",
    "toggle-file-tree": "Alternar árbol de archivos",
    "new-terminal": "Nuevo terminal",
    "close-terminal": "Cerrar pestaña de terminal",
    "new-project": "Nuevo proyecto",
    "close-project": "Cerrar proyecto",
    "close-file": "Cerrar archivo",
    "next-file": "Siguiente archivo",
    "prev-file": "Archivo anterior",
    "save-file": "Save File",
    "save-all-files": "Save All Files",
    "reopen-closed-tab": "Reopen Closed File",
    "format-document": "Format Document",
    "toggle-comment": "Toggle Line Comment",
    "toggle-word-wrap": "Toggle Word Wrap",
    "find-in-file": "Find in File",
    "replace-in-file": "Replace in File",
    "duplicate-line": "Duplicate Line Down",
    "move-line-up": "Move Line Up",
    "move-line-down": "Move Line Down",
    "toggle-git-panel": "Toggle Source Control (Git)",
    "zoom-in": "Zoom In Interface",
    "zoom-out": "Zoom Out Interface",
    "zoom-reset": "Reset Zoom Interface",
    "open-hotkeys": "Open Keyboard Shortcuts",
    "open-providers": "Open AI Providers",
    "open-mcp": "Open MCP Server Settings",
  },
};

const DE_LOCALE: HotkeysLocale = {
  all: "Alle",
  categoriesLabel: "Kategorien",
  searchPlaceholder: "Tastenkürzel nach Befehl, Taste oder Kategorie suchen...",
  commandsConfigured: (count: number) => `${count} Befehle konfiguriert`,
  statsText: (matched, total) => (matched === total ? `${total} Tastenkürzel` : `${matched} von ${total}`),
  pressCombo: "Tastenkombination drücken... (Esc zum Abbrechen)",
  cancelEsc: "Esc zum Abbrechen",
  rebindTooltip: "Klicken, um Tastenkürzel neu zuzuweisen",
  resetTooltip: "Auf Standard zurücksetzen",
  footerTip: "Klicken Sie auf eine Kombination, um sie neu zu belegen. Drücken Sie Escape zum Abbrechen oder die Reset-Taste.",
  emptyTitle: "Keine Tastenkürzel gefunden",
  emptyDesc: "Versuchen Sie eine andere Suche oder wählen Sie eine andere Kategorie.",
  resetFilters: "Filter zurücksetzen",
  unassigned: "Nicht zugewiesen",
  chordThen: "dann",
  categories: {
    navigation: { title: "Navigation & Tabs", short: "Navigation" },
    search: { title: "Suche & Code-Finder", short: "Suche" },
    chat: { title: "KI-Chat & Prompts", short: "Chat" },
    workspace: { title: "Arbeitsbereich & Layout", short: "Bereich" },
    terminal: { title: "Integriertes Terminal", short: "Terminal" },
    project: { title: "Projekte & Ordner", short: "Projekte" },
    editor: { title: "Editor & Codedateien", short: "Editor" },
  },
  commands: {
    "open-settings": "Einstellungen öffnen",
    "quick-search": "Schnellsuche nach Datei",
    "open-search-in-code": "Im Code suchen",
    "focus-input": "Eingabefeld fokussieren",
    "new-chat": "Neuer Chat",
    "next-chat": "Nächster Chat",
    "prev-chat": "Vorheriger Chat",
    "clear-chat": "Chat leeren",
    "toggle-terminal": "Terminal umschalten",
    "toggle-file-tree": "Dateibaum umschalten",
    "new-terminal": "Neues Terminal",
    "close-terminal": "Terminal schließen",
    "new-project": "Neues Projekt",
    "close-project": "Projekt schließen",
    "close-file": "Datei schließen",
    "next-file": "Nächste Datei",
    "prev-file": "Vorherige Datei",
    "save-file": "Save File",
    "save-all-files": "Save All Files",
    "reopen-closed-tab": "Reopen Closed File",
    "format-document": "Format Document",
    "toggle-comment": "Toggle Line Comment",
    "toggle-word-wrap": "Toggle Word Wrap",
    "find-in-file": "Find in File",
    "replace-in-file": "Replace in File",
    "duplicate-line": "Duplicate Line Down",
    "move-line-up": "Move Line Up",
    "move-line-down": "Move Line Down",
    "toggle-git-panel": "Toggle Source Control (Git)",
    "zoom-in": "Zoom In Interface",
    "zoom-out": "Zoom Out Interface",
    "zoom-reset": "Reset Zoom Interface",
    "open-hotkeys": "Open Keyboard Shortcuts",
    "open-providers": "Open AI Providers",
    "open-mcp": "Open MCP Server Settings",
  },
};

const FR_LOCALE: HotkeysLocale = {
  all: "Tous",
  categoriesLabel: "Catégories",
  searchPlaceholder: "Rechercher des raccourcis par commande, touche ou catégorie...",
  commandsConfigured: (count: number) => `${count} commandes configurées`,
  statsText: (matched, total) => (matched === total ? `${total} raccourcis` : `${matched} sur ${total}`),
  pressCombo: "Appuyez sur la combinaison de touches... (Échap pour annuler)",
  cancelEsc: "Appuyez sur Échap pour annuler",
  rebindTooltip: "Cliquez pour réassigner le raccourci",
  resetTooltip: "Réinitialiser au raccourci par défaut",
  footerTip: "Cliquez sur un raccourci pour le modifier. Appuyez sur Échap pour annuler ou utilisez le bouton de réinitialisation.",
  emptyTitle: "Aucun raccourci trouvé",
  emptyDesc: "Essayez de rechercher un autre nom ou choisissez une autre catégorie.",
  resetFilters: "Réinitialiser les filtres",
  unassigned: "Non assigné",
  chordThen: "puis",
  categories: {
    navigation: { title: "Navigation et onglets", short: "Navigation" },
    search: { title: "Recherche et fichiers", short: "Recherche" },
    chat: { title: "Chat et IA", short: "Chat" },
    workspace: { title: "Espace de travail et disposition", short: "Espace" },
    terminal: { title: "Terminal intégré", short: "Terminal" },
    project: { title: "Projets et dossiers", short: "Projets" },
    editor: { title: "Éditeur et fichiers de code", short: "Éditeur" },
  },
  commands: {
    "open-settings": "Ouvrir les paramètres",
    "quick-search": "Recherche rapide de fichier",
    "open-search-in-code": "Rechercher dans le code",
    "focus-input": "Cibler le champ de saisie",
    "new-chat": "Nouveau chat",
    "next-chat": "Chat suivant",
    "prev-chat": "Chat précédent",
    "clear-chat": "Effacer le chat",
    "toggle-terminal": "Basculer le terminal",
    "toggle-file-tree": "Basculer l'arborescence",
    "new-terminal": "Nouveau terminal",
    "close-terminal": "Fermer le terminal",
    "new-project": "Nouveau projet",
    "close-project": "Fermer le projet",
    "close-file": "Fermer le fichier",
    "next-file": "Fichier suivant",
    "prev-file": "Fichier précédent",
    "save-file": "Save File",
    "save-all-files": "Save All Files",
    "reopen-closed-tab": "Reopen Closed File",
    "format-document": "Format Document",
    "toggle-comment": "Toggle Line Comment",
    "toggle-word-wrap": "Toggle Word Wrap",
    "find-in-file": "Find in File",
    "replace-in-file": "Replace in File",
    "duplicate-line": "Duplicate Line Down",
    "move-line-up": "Move Line Up",
    "move-line-down": "Move Line Down",
    "toggle-git-panel": "Toggle Source Control (Git)",
    "zoom-in": "Zoom In Interface",
    "zoom-out": "Zoom Out Interface",
    "zoom-reset": "Reset Zoom Interface",
    "open-hotkeys": "Open Keyboard Shortcuts",
    "open-providers": "Open AI Providers",
    "open-mcp": "Open MCP Server Settings",
  },
};

const JA_LOCALE: HotkeysLocale = {
  all: "すべて",
  categoriesLabel: "カテゴリ",
  searchPlaceholder: "コマンド名、キー、またはカテゴリでショートカットを検索...",
  commandsConfigured: (count: number) => `${count} 件のコマンドを設定済み`,
  statsText: (matched, total) => (matched === total ? `${total} 件のショートカット` : `${matched} / ${total} 件を表示`),
  pressCombo: "キーの組み合わせを押してください... (Esc でキャンセル)",
  cancelEsc: "Esc でキャンセル",
  rebindTooltip: "クリックしてショートカットを再設定",
  resetTooltip: "デフォルトに戻す",
  footerTip: "キーの組み合わせをクリックして再割り当てできます。Esc でキャンセル、リセットボタンで初期値に戻せます。",
  emptyTitle: "ショートカットが見つかりません",
  emptyDesc: "別の検索キーワードを試すか、カテゴリを変更してください。",
  resetFilters: "フィルターをリセット",
  unassigned: "未設定",
  chordThen: "次に",
  categories: {
    navigation: { title: "ナビゲーションとタブ", short: "ナビ" },
    search: { title: "検索とファイル", short: "検索" },
    chat: { title: "AIチャットとプロンプト", short: "チャット" },
    workspace: { title: "ワークスペースとレイアウト", short: "環境" },
    terminal: { title: "統合ターミナル", short: "ターミナル" },
    project: { title: "プロジェクトとフォルダ", short: "プロジェクト" },
    editor: { title: "エディタとコードファイル", short: "エディタ" },
  },
  commands: {
    "open-settings": "設定を開く",
    "quick-search": "クイックファイル検索",
    "open-search-in-code": "コード内を検索",
    "focus-input": "入力フィールドにフォーカス",
    "new-chat": "新しいチャット",
    "next-chat": "次のチャット",
    "prev-chat": "前のチャット",
    "clear-chat": "チャットをクリア",
    "toggle-terminal": "ターミナルの切り替え",
    "toggle-file-tree": "ファイルツリーの切り替え",
    "new-terminal": "新規ターミナル",
    "close-terminal": "ターミナルを閉じる",
    "new-project": "新規プロジェクト",
    "close-project": "プロジェクトを閉じる",
    "close-file": "ファイルを閉じる",
    "next-file": "次のファイル",
    "prev-file": "前のファイル",
    "save-file": "Save File",
    "save-all-files": "Save All Files",
    "reopen-closed-tab": "Reopen Closed File",
    "format-document": "Format Document",
    "toggle-comment": "Toggle Line Comment",
    "toggle-word-wrap": "Toggle Word Wrap",
    "find-in-file": "Find in File",
    "replace-in-file": "Replace in File",
    "duplicate-line": "Duplicate Line Down",
    "move-line-up": "Move Line Up",
    "move-line-down": "Move Line Down",
    "toggle-git-panel": "Toggle Source Control (Git)",
    "zoom-in": "Zoom In Interface",
    "zoom-out": "Zoom Out Interface",
    "zoom-reset": "Reset Zoom Interface",
    "open-hotkeys": "Open Keyboard Shortcuts",
    "open-providers": "Open AI Providers",
    "open-mcp": "Open MCP Server Settings",
  },
};

const KO_LOCALE: HotkeysLocale = {
  all: "전체",
  categoriesLabel: "카테고리",
  searchPlaceholder: "명령어 이름, 단축키 또는 카테고리로 검색...",
  commandsConfigured: (count: number) => `${count}개 명령어 설정됨`,
  statsText: (matched, total) => (matched === total ? `${total}개 단축키` : `${matched} / ${total}`),
  pressCombo: "키 조합을 누르세요... (Esc로 취소)",
  cancelEsc: "Esc로 취소",
  rebindTooltip: "클릭하여 단축키 재지정",
  resetTooltip: "기본값으로 초기화",
  footerTip: "키 조합을 클릭하여 재지정하세요. Esc로 취소하거나 초기화 버튼으로 기본 설정으로 복원할 수 있습니다.",
  emptyTitle: "단축키를 찾을 수 없습니다",
  emptyDesc: "다른 검색어를 입력하거나 카테고리를 변경해 보세요.",
  resetFilters: "필터 초기화",
  unassigned: "지정되지 않음",
  chordThen: "이어서",
  categories: {
    navigation: { title: "탐색 및 탭", short: "탐색" },
    search: { title: "검색 및 코드 찾기", short: "검색" },
    chat: { title: "AI 채팅 및 프롬프트", short: "채팅" },
    workspace: { title: "워크스페이스 및 레이아웃", short: "작업공간" },
    terminal: { title: "통합 터미널", short: "터미널" },
    project: { title: "프로젝트 및 폴더", short: "프로젝트" },
    editor: { title: "편집기 및 코드 파일", short: "편집기" },
  },
  commands: {
    "open-settings": "설정 열기",
    "quick-search": "빠른 파일 찾기",
    "open-search-in-code": "코드 전체 검색",
    "focus-input": "입력창 포커스",
    "new-chat": "새 채팅",
    "next-chat": "다음 채팅",
    "prev-chat": "이전 채팅",
    "clear-chat": "채팅 비우기",
    "toggle-terminal": "터미널 켜기/끄기",
    "toggle-file-tree": "파일 탐색기 켜기/끄기",
    "new-terminal": "새 터미널 열기",
    "close-terminal": "터미널 닫기",
    "new-project": "새 프로젝트",
    "close-project": "프로젝트 닫기",
    "close-file": "파일 닫기",
    "next-file": "다음 파일",
    "prev-file": "이전 파일",
    "save-file": "Save File",
    "save-all-files": "Save All Files",
    "reopen-closed-tab": "Reopen Closed File",
    "format-document": "Format Document",
    "toggle-comment": "Toggle Line Comment",
    "toggle-word-wrap": "Toggle Word Wrap",
    "find-in-file": "Find in File",
    "replace-in-file": "Replace in File",
    "duplicate-line": "Duplicate Line Down",
    "move-line-up": "Move Line Up",
    "move-line-down": "Move Line Down",
    "toggle-git-panel": "Toggle Source Control (Git)",
    "zoom-in": "Zoom In Interface",
    "zoom-out": "Zoom Out Interface",
    "zoom-reset": "Reset Zoom Interface",
    "open-hotkeys": "Open Keyboard Shortcuts",
    "open-providers": "Open AI Providers",
    "open-mcp": "Open MCP Server Settings",
  },
};

const TR_LOCALE: HotkeysLocale = {
  all: "Tümü",
  categoriesLabel: "Kategoriler",
  searchPlaceholder: "Komut adı, tuş veya kategoriye göre ara...",
  commandsConfigured: (count: number) => `${count} komut yapılandırıldı`,
  statsText: (matched, total) => (matched === total ? `${total} kısayol` : `${matched} / ${total}`),
  pressCombo: "Tuş kombinasyonuna basın... (İptal için Esc)",
  cancelEsc: "İptal için Esc tuşuna basın",
  rebindTooltip: "Kısayolu yeniden atamak için tıklayın",
  resetTooltip: "Varsayılana sıfırla",
  footerTip: "Yeniden atamak için herhangi bir kısayola tıklayın. Kaydı iptal etmek için Escape tuşuna veya sıfırlama butonuna basın.",
  emptyTitle: "Eşleşen kısayol bulunamadı",
  emptyDesc: "Farklı bir komut adı deneyin veya başka bir kategori seçin.",
  resetFilters: "Filtreleri Sıfırla",
  unassigned: "Atanmadı",
  chordThen: "ardından",
  categories: {
    navigation: { title: "Gezinme ve Sekmeler", short: "Gezinme" },
    search: { title: "Arama ve Dosyalar", short: "Arama" },
    chat: { title: "Yapay Zeka Sohbeti", short: "Sohbet" },
    workspace: { title: "Çalışma Alanı ve Düzen", short: "Alan" },
    terminal: { title: "Entegre Terminal", short: "Terminal" },
    project: { title: "Projeler ve Klasörler", short: "Projeler" },
    editor: { title: "Düzenleyici ve Kod Dosyaları", short: "Düzenleyici" },
  },
  commands: {
    "open-settings": "Ayarları Aç",
    "quick-search": "Hızlı Dosya Arama",
    "open-search-in-code": "Kod İçinde Ara",
    "focus-input": "Giriş Alanına Odaklan",
    "new-chat": "Yeni Sohbet",
    "next-chat": "Sonraki Sohbet",
    "prev-chat": "Önceki Sohbet",
    "clear-chat": "Sohbeti Temizle",
    "toggle-terminal": "Terminali Aç/Kapat",
    "toggle-file-tree": "Dosya Ağacını Aç/Kapat",
    "new-terminal": "Yeni Terminal Sekmesi",
    "close-terminal": "Terminal Sekmesini Kapat",
    "new-project": "Yeni Proje",
    "close-project": "Projeyi Kapat",
    "close-file": "Dosyayı Kapat",
    "next-file": "Sonraki Dosya",
    "prev-file": "Önceki Dosya",
    "save-file": "Save File",
    "save-all-files": "Save All Files",
    "reopen-closed-tab": "Reopen Closed File",
    "format-document": "Format Document",
    "toggle-comment": "Toggle Line Comment",
    "toggle-word-wrap": "Toggle Word Wrap",
    "find-in-file": "Find in File",
    "replace-in-file": "Replace in File",
    "duplicate-line": "Duplicate Line Down",
    "move-line-up": "Move Line Up",
    "move-line-down": "Move Line Down",
    "toggle-git-panel": "Toggle Source Control (Git)",
    "zoom-in": "Zoom In Interface",
    "zoom-out": "Zoom Out Interface",
    "zoom-reset": "Reset Zoom Interface",
    "open-hotkeys": "Open Keyboard Shortcuts",
    "open-providers": "Open AI Providers",
    "open-mcp": "Open MCP Server Settings",
  },
};

const BE_LOCALE: HotkeysLocale = {
  ...RU_LOCALE,
  categories: {
    ...RU_LOCALE.categories,
  },
};

const EN_LOCALE: HotkeysLocale = {
  all: "All",
  categoriesLabel: "Categories",
  searchPlaceholder: "Search shortcuts by command name, key, or category...",
  commandsConfigured: (count: number) => `${count} command${count === 1 ? "" : "s"} configured`,
  statsText: (matched, total) => (matched === total ? `${total} shortcuts` : `Showing ${matched} of ${total}`),
  pressCombo: "Press key combination... (Esc to cancel)",
  cancelEsc: "Press Esc to cancel",
  rebindTooltip: "Click to rebind shortcut",
  resetTooltip: "Reset to default shortcut",
  footerTip: "Click any key combination to reassign it. Press Escape to cancel recording, or use the reset button to restore default shortcuts.",
  emptyTitle: "No shortcuts match your search",
  emptyDesc: "Try searching for a different command name or key combination.",
  resetFilters: "Reset Filters",
  unassigned: "Unassigned",
  chordThen: "then",
  categories: {
    navigation: { short: "Navigation", title: "Navigation & Tabs" },
    search: { short: "Search", title: "Search & Code Finder" },
    chat: { short: "Chat", title: "AI Chat & Prompts" },
    workspace: { short: "Workspace", title: "Workspace & Layout" },
    terminal: { short: "Terminal", title: "Integrated Terminal" },
    project: { short: "Projects", title: "Projects & Folders" },
    editor: { short: "Editor", title: "Editor & Code Files" },
  },
  commands: {},
};

export function getHotkeysLocale(lang: LangCode): HotkeysLocale {
  switch (lang) {
    case "Russian":
      return RU_LOCALE;
    case "Ukrainian":
      return UK_LOCALE;
    case "Belarusian":
      return BE_LOCALE;
    case "Chinese":
    case "ChineseSimplified":
      return ZH_LOCALE;
    case "Spanish":
      return ES_LOCALE;
    case "German":
      return DE_LOCALE;
    case "French":
      return FR_LOCALE;
    case "Japanese":
      return JA_LOCALE;
    case "Korean":
      return KO_LOCALE;
    case "Turkish":
      return TR_LOCALE;
    case "English":
      return EN_LOCALE;
    default:
      return EN_LOCALE;
  }
}
